version: "3.8"

services:
  extension:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: chrome-extension-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.bun
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    command: bun run dev
    tty: true
    stdin_open: true
